### PR TITLE
Fixes issue where AI would run a non-existent Phase 4

### LINKED ISSUE #28: Phase 2 bug when playing against AI
When playing against AI, phase 2 (the phase in which the player can buy and customise robotics) skips.

### PR DESCRIPTION
**Pull request by Mart500**
This somehow created a timeout which would run next phase. 

closes #28

### CODE REVIEW

**Review by RobinStephenson — CHANGES_REQUESTED** [review]
Looks good but just need to update the header with what you changed.
Once youve done that its good to merge

File: core/src/io/github/teamfractal/RoboticonQuest.java [hunk 1]
```diff
@@ -1,4 +1,7 @@
-
+/*  JBT Assessment 4 Page: http://robins.tech/jbt/assfour.html
+ *  JBT Changes to this file:
+ *  Removed partial patch for a bug, which was fixed elsewhere
```
Comment (RobinStephenson) [inline core/src/io/github/teamfractal/RoboticonQuest.java]: This is quite hard to understand what you mean. From someone who doesnt know what the bug is or where the elsewhere is as they wont be looking at it in a PR like us

File: core/src/io/github/teamfractal/actors/GameScreenActors.java [hunk 2]
```diff
@@ -33,6 +33,7 @@
 import io.github.teamfractal.exception.TransactionException;
 import io.github.teamfractal.screens.AbstractAnimationScreen;
 import io.github.teamfractal.screens.GameScreen;
+import sun.font.TrueTypeFont;
```
Comment (RobinStephenson) [inline core/src/io/github/teamfractal/actors/GameScreenActors.java]: Whats this?

**Review by RobinStephenson — CHANGES_REQUESTED** [review]
Some minor changes but looks good otherwise

**Review by RobinStephenson — APPROVED** [review]
